### ISSUE TITLE
Prettier config and eslint config conflicts

### ISSUE THREAD

**Issue by ghost** [betalectic-reusejs/shared-configs#5]
Hi Shrey,

I've followed the documentation of the shared config eslint node package - https://github.com/betalectic-reusejs/shared-configs/blob/main/packages/shared-config-eslint-node/README.md

Eslint seems to be working, but I was seeing so many errors when I open files and errors such as tab errors, and custom require functions errors. I was attaching the screenshots to get more idea on these errors.

<img width="1440" alt="Screenshot 2023-03-13 at 11 52 50 AM" src="https://user-images.githubusercontent.com/87059448/224623194-db29aabf-e0ec-430d-8623-8148a82c9fd7.png">

<img width="1439" alt="Screenshot 2023-03-13 at 11 52 58 AM" src="https://user-images.githubusercontent.com/87059448/224623280-dbb33864-491c-47bd-b3f1-70041dd9c7ed.png">

<img width="1440" alt="Screenshot 2023-03-13 at 11 52 39 AM" src="https://user-images.githubusercontent.com/87059448/224623310-e8e65882-a320-46e5-a0bc-a61137fd2e76.png">

Is it possible to resolve the conflicts between the vs code prettier config and eslint shared config that is provided by this package?

- Moreover, the custom require functions such as `requireUtils()`, `requireValidator()` errors should also be resolved.

**Comment by ShreyDhyani** [comment]
@maheshmuttinti pls refer to Documentation in following links:
https://github.com/betalectic-reusejs/shared-configs/blob/main/Global_Variables.md
https://github.com/betalectic-reusejs/shared-configs/blob/main/Prettier-EsLint-Conflict-Resolution.md

**Comment by ShreyDhyani** [comment]
@maheshmuttinti Also the radical-mf code base is in nobejs. 
So please refer to 
https://github.com/betalectic-reusejs/shared-configs/tree/main/packages/shared-config-eslint-nobejs for EsLint  https://github.com/betalectic-reusejs/shared-configs/tree/main/packages/shared-config-prettier-node for Prettier

**Comment by ShreyDhyani** [comment]
Setup For Shared configuration **Done**. Closing.
