### ISSUE TITLE
EsLint seems too opinionated

### ISSUE THREAD

**Issue by rjvim** [betalectic-reusejs/shared-configs#6]
https://github.com/betalectic-reusejs/shared-configs/blob/main/packages/shared-config-eslint-node/eslint-config.js

Why do we have following rules:

```
  rules: {
    indent: ["error", "tab"],
    "linebreak-style": ["error", "unix"],
    quotes: ["error", "single"],
    semi: ["error", "always"],
  },
  ```

It insists that quotes should be "single" and others. May be developers have preference over these, so, we should remove "rules" from here. Anyway we are extending -   `extends: ["eslint:recommended"]`

**Comment by ShreyDhyani** [comment]
Issues Noted and will be Discussed and Resolved in Future Release

**Comment by ShreyDhyani** [comment]
@rjvim Removed rules from EsLint configs for all platforms(Node, NobeJS, React and React-Native). Pls update to new configuration or add Dependabot using following guide: https://github.com/betalectic-reusejs/shared-configs/blob/main/README.md
